# Generated by Django 3.0.2 on 2022-07-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('image', models.FileField(default='defult.jpg', upload_to='static/image/women')),
            ],
            options={
                'db_table': 'AddProduct',
            },
        ),
    ]
