# Generated by Django 3.0.2 on 2022-07-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone1', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone2', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=80)),
                ('Quantity', models.CharField(max_length=10)),
                ('P_name', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=60)),
                ('Country', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
