# Generated by Django 3.0.2 on 2022-07-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('caption2', models.CharField(default='', max_length=50)),
                ('image', models.FileField(default='defult.jpg', upload_to='static/image/background')),
            ],
            options={
                'db_table': 'ProductDetail',
            },
        ),
    ]
