# Generated by Django 3.0.2 on 2022-07-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220718_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='decs',
            field=models.TextField(max_length=50),
        ),
    ]
