# Generated by Django 3.0.2 on 2022-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone1', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=150)),
                ('Phone2', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Quantity', models.CharField(max_length=150)),
                ('P_name', models.CharField(max_length=15)),
                ('City', models.CharField(max_length=150)),
                ('Country', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=150)),
                ('Zipcode', models.CharField(max_length=15)),
            ],
        ),
    ]
