# Generated by Django 3.0.2 on 2022-07-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_checkout'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checkout',
            table='checkout',
        ),
    ]
